services:
  manul-bot:
    build: .
    container_name: manul_garage_bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./database.db:/app/database.db
      - ./uploads:/app/uploads
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"