services:
  db:
    image: postgres:15
    container_name: manul_garage_db
    restart: always
    env_file: .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - TZ=Asia/Jerusalem
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - manul_network

  manul-bot:
    build: .
    container_name: manul_garage_bot
    restart: always
    depends_on:
      - db
    dns:
      - 8.8.8.8
      - 1.1.1.1
    env_file: .env
    environment:
      - TZ=Asia/Jerusalem
      - PYTHONPATH=/app
      - DB_HOST=db
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    command: ["python", "main.py"]
    networks:
      - manul_network

  manul-hunter:
    build: .
    container_name: manul_garage_hunter
    restart: always
    depends_on:
      - db
    dns:
      - 8.8.8.8
      - 1.1.1.1
    env_file: .env
    environment:
      - TZ=Asia/Jerusalem
      - PYTHONPATH=/app
      - DB_HOST=db
    volumes:
      - .:/app
    command: python -m src.services.scrapers.hunter
    networks:
      - manul_network

volumes:
  postgres_data:

networks:
  manul_network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400